"""Add user-task relationship

Revision ID: 66a68fd79687
Revises: 63ef982ca189
Create Date: 2024-05-30 13:38:06.588766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a68fd79687'
down_revision = '63ef982ca189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
